version: '1.0.{build}'
image: Visual Studio 2019
branches:
  only:
  - master
init:
  - cmd: git config --global core.autocrlf true
before_build:
  - cmd: dotnet --version
  - cmd: dotnet restore ./ConsoleGenericStrategy/ConsoleGenericStrategy.csproj --verbosity m
build_script:
  - cmd: dotnet publish ./ConsoleGenericStrategy/ConsoleGenericStrategy.csproj
clone_depth: 1
test_script:
  - cmd: dotnet restore ./ConsoleGenericStrategy.Tests.csproj --verbosity m
  - cmd: dotnet test ./ConsoleGenericStrategy.Tests.csproj
deploy: off